### ISSUE TITLE
How set connection to user

### ISSUE THREAD

**Issue by maathor** [pschmitt/guacapy#11]
Hi, 

Would like to know:
  -  I manager t create user 
  - and connections easily,

but I don't understand how to associate a connection to a user.

Did you try to do this ?
Thanks a lot,

Marc

**Comment by maathor** [comment]
```
    def add_connection_permission(self, username, payload, datasource=None):
        '''
        Example payload:
        [{"op":"add","path":"/connectionPermission/<id_connection>",value:"READ"]
        '''
        if not datasource:
            datasource = self.primary_datasource
        return self.__auth_request(
            method='PATCH',
            url='{}/session/data/{}/users/{}/permissions'.format(
                self.REST_API,
                datasource,
                username
            ),
            payload=payload,
            json_response=False
        )

```

**Comment by eric-gunn** [comment]
@pschmitt I would also like to know how to associate users with connections, or users with groups.

**Comment by tt2468** [comment]
An example payload for this is `[{"op":"add","path":"/connectionPermissions/23","value":"READ"}]`

Where 23 is the id of the connection.

**Comment by mjbright** [comment]
Hmm, I've been searching how to do this and am rather surprised to come across this closed issue.

The proposed solution from @maathor has a typo, it should be using the path ```/connectionPermissions/<id_connection>``` in the example payload, NOT ``/connectionPermission/<id_connection>```

Thanks to @maathor for this example though - at last I have this working and this could help others.

The other thing which surprises me is that the issue was closed without this really useful method being added to the module.  This makes me wonder if this is not the right way of doing this - I've found the guacamole documentation somewhat lacking on this point.  For the moment I'll just fork and use my copy, but that doesn't seem right.

It was only through much googling that I noticed here https://docs.netcubed.io/products/guacamole/api/ and example with connectionPermissions.
