### ISSUE TITLE
Getting this error while adding new connections   "b'{"message":"Session not associated with authentication provider \\"

### ISSUE THREAD

**Issue by Shubham3521** [pschmitt/guacapy#32]
>>>p.add_connection(payload='json_string', datasource=json_string)                     
b'{"message":"Session not associated with authentication provider \\"{\'name\': \'iaas-067-mgt01 (Admin)\', \'parentIdentifier\': \'4\', \'protocol\': \'rdp\', \'attributes\': {\'max-connections\': \'\', \'max-connections-per-user\': \'\'}, \'activeConnections\': 0, \'parameters\': {\'port\': \'3389\', \'enable-menu-animations\': \'true\', \'enable-desktop-composition\': \'true\', \'hostname\': \'iaas-067-mgt01.vcloud\', \'color-depth\': \'32\', \'enable-font-smoothing\': \'true\', \'ignore-cert\': \'true\', \'enable-drive\': \'true\', \'enable-full-window-drag\': \'true\', \'security\': \'any\', \'password\': \'XXX\', \'enable-wallpaper\': \'true\', \'create-drive-path\': \'true\', \'enable-theming\': \'true\', \'username\': \'Administrator\', \'console\': \'true\', \'disable-audio\': \'true\', \'domain\': \'iaas-067-mgt01.vcloud\'}}\\".","translatableMessage":{"key":"Session not associated with authentication provider \\"{\'name\': \'iaas-067-mgt01 (Admin)\', \'parentIdentifier\': \'4\', \'protocol\': \'rdp\', \'attributes\': {\'max-connections\': \'\', \'max-connections-per-user\': \'\'}, \'activeConnections\': 0, \'parameters\': {\'port\': \'3389\', \'enable-menu-animations\': \'true\', \'enable-desktop-composition\': \'true\', \'hostname\': \'iaas-067-mgt01.vcloud\', \'color-depth\': \'32\', \'enable-font-smoothing\': \'true\', \'ignore-cert\': \'true\', \'enable-drive\': \'true\', \'enable-full-window-drag\': \'true\', \'security\': \'any\', \'password\': \'XXX\', \'enable-wallpaper\': \'true\', \'create-drive-path\': \'true\', \'enable-theming\': \'true\', \'username\': \'Administrator\', \'console\': \'true\', \'disable-audio\': \'true\', \'domain\': \'iaas-067-mgt01.vcloud\'}}\\".","variables":null},"statusCode":null,"expected":null,"type":"NOT_FOUND"

**Comment by pschmitt** [comment]
Looks like you tried to add a host using the example payload.
What exactly did you attempt to do here? I need to see actual code.
