### ISSUE TITLE
Incorrect Padding

### ISSUE THREAD

**Issue by benspring** [pschmitt/guacapy#53]
I'm attempting to use guacapy with Python3, but am encountering the following error:

It works perfectly with Python2, just doesn't like 3.

![image](https://user-images.githubusercontent.com/23476599/115706127-361fa500-a365-11eb-9c47-65008354f91b.png)

**Comment by pschmitt** [comment]
Screenshots are great, actual code is better. Can you please add a snippet here that reproduces this error?

**Comment by pschmitt** [comment]
Closing.
