### ISSUE TITLE
totp token bug

### ISSUE THREAD

**Issue by nicolasVaye** [pschmitt/guacapy#69]
Hello,

my colleague jerome Alet has provided to you 18 months ago, a code/request for totp support. I just discover a little problem these last days : 
The totp token consists of 6 digits and when the totp code computed by the method get_hotp_token is < 100000, the int value don't have 6 digits and the method get_totp_token return a bad token.
So i changed the get_totp_token at my business work  like this :

def get_totp_token(secret):
    value = get_hotp_token(secret, intervals_no=int(time.time()) // 30)
    return str(value).rjust(6, '0') # 6 digits for totp token (pad with 0 char)

best regards.

**Comment by pschmitt** [comment]
Thanks for reporting. Can you open a MR with that fix?

**Comment by nicolasVaye** [comment]
PR #70 submitted
