### ISSUE TITLE
Can you give me an example about how to use the guacapy in python flask RESTful framework

### ISSUE THREAD

**Issue by feifeixj** [pschmitt/guacapy#7]
Hi, I'm very confused that I installed the package guacapy with guacamole and simplejson. However, I don't know how to use the package in Pycharm.

for example I wrote the codes:
import guacapy

client = guacapy.Guacamole("192.168.20.137","root","root")
print client

I don't know the username and password whether are the guacamole , what's more, the wrong info is 

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.20.137', port=443): Max retries exceeded with url: /api/tokens (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000002B6CF28>: Failed to establish a new connection: [Errno 10060] ',))`
I don't understand the use of  '/api/tokens ' .

I am going to use the package to add new authentication info  to Guacamole's mysql database. I don't know whether this package can work.

Thanks!

**Comment by lichao0x7cc** [comment]
Can you paste your guacamole server address.
otherwise, you can use browser devloper tools check request url address. when you login the guacamole
